-- Escribe todos los caracteres de la columna en minuscula.
SELECT ID_EMPLEADO,LOWER(NOMBRE) AS NOMBRE_MINUSCULAS,LOWER(APELLIDO) AS APELLIDO_MINUSCULAS,LOWER(DIRECCION) AS DIRECCION_MINUSCULAS
FROM EMPLEADOS2;